# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            By-Serena
tagline:          The Jekyll Butler
description:      Base theme for Jekyll themes by @mdo.
url:              http://astrolope.github.io/hbs

author:
  name:           Mark Otto
  url:            https://twitter.com/mdo

paginate:         1
destination:      /hbs/hats

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/poole
