# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            The West Coast Washing Machine
tagline:          ''
description:      'The West Coast Washing Machine</br></br>Rinsing all your dirty laundry so you dont have to.'
url:              http://westcoastwashingmachine.com

creator:
  name:           'Garrett Criss'
  url:            http://lycrabeats.com



paginate:         4

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
